# Generated by Django 2.0.3 on 2018-05-04 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb_id', models.CharField(blank=True, max_length=200, null=True)),
                ('fb_email', models.CharField(blank=True, max_length=200, null=True)),
                ('fb_access_token', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oauth_token', models.CharField(blank=True, editable=False, max_length=200, null=True)),
                ('oauth_secret', models.CharField(max_length=200)),
                ('profile_image_url', models.URLField(blank=True, max_length=100, null=True)),
                ('social_id', models.CharField(blank=True, max_length=200, null=True)),
                ('social_email', models.CharField(blank=True, max_length=200, null=True)),
                ('social_usename', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TwitterProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oauth_token', models.CharField(blank=True, editable=False, max_length=200, null=True)),
                ('oauth_secret', models.CharField(max_length=200)),
                ('tw_image_url', models.URLField(blank=True, max_length=100, null=True)),
                ('tw_id', models.CharField(blank=True, max_length=200, null=True)),
                ('tw_username', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_text', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='twitterprofile',
            name='tw_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialtracker.User'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialtracker.User'),
        ),
        migrations.AddField(
            model_name='facebookprofile',
            name='fb_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialtracker.User'),
        ),
    ]
