# Generated by Django 2.0.4 on 2018-04-25 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_analytics', '0002_fackbookprofile_twitterprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fackbookprofile',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='twitterprofile',
            old_name='user_id',
            new_name='user',
        ),
    ]
