# Generated by Django 2.0.4 on 2018-05-01 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialtracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fackbookprofile',
            table='FackbookProfile',
        ),
        migrations.AlterModelTable(
            name='twitterprofile',
            table='TwitterProfile',
        ),
    ]
