# Generated by Django 2.0.4 on 2018-05-02 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialtracker', '0002_auto_20180501_0528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fackbookprofile',
            name='f_email',
        ),
        migrations.RemoveField(
            model_name='fackbookprofile',
            name='f_profile_image_url',
        ),
        migrations.RemoveField(
            model_name='fackbookprofile',
            name='f_usename',
        ),
        migrations.RemoveField(
            model_name='fackbookprofile',
            name='f_user_id',
        ),
        migrations.RemoveField(
            model_name='twitterprofile',
            name='t_email',
        ),
        migrations.RemoveField(
            model_name='twitterprofile',
            name='t_profile_image_url',
        ),
        migrations.RemoveField(
            model_name='twitterprofile',
            name='t_usename',
        ),
        migrations.RemoveField(
            model_name='twitterprofile',
            name='t_user_id',
        ),
        migrations.AlterField(
            model_name='fackbookprofile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='twitterprofile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
