# Generated by Django 2.0.4 on 2018-05-16 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialtracker', '0002_auto_20180516_0112'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_text', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='facebookprofile',
            name='fb_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialtracker.User'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialtracker.User'),
        ),
        migrations.AlterField(
            model_name='twitterprofile',
            name='tw_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialtracker.User'),
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
