# Generated by Django 2.0.3 on 2018-04-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialtracker', '0003_auto_20180406_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='social_email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='social_use_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='social_usename',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
