# Generated by Django 2.0.4 on 2018-05-02 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialtracker', '0003_auto_20180502_0114'),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('g_token', models.CharField(blank=True, max_length=100, null=True)),
                ('g_secret', models.CharField(blank=True, max_length=100, null=True)),
                ('g_result', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'GithubProfile',
            },
        ),
    ]
