# Generated by Django 2.0.4 on 2018-05-15 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialtracker', '0004_githubprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
