# Generated by Django 2.0.3 on 2018-05-02 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialtracker', '0004_auto_20180425_2239'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb_id', models.CharField(blank=True, max_length=200, null=True)),
                ('fb_email', models.CharField(blank=True, max_length=200, null=True)),
                ('fb_access_token', models.CharField(blank=True, max_length=200, null=True)),
                ('fb_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialtracker.User')),
            ],
        ),
        migrations.CreateModel(
            name='TwitterProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oauth_token', models.CharField(blank=True, editable=False, max_length=200, null=True)),
                ('oauth_secret', models.CharField(max_length=200)),
                ('tw_image_url', models.URLField(blank=True, max_length=100, null=True)),
                ('tw_id', models.CharField(blank=True, max_length=200, null=True)),
                ('tw_username', models.CharField(blank=True, max_length=200, null=True)),
                ('tw_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialtracker.User')),
            ],
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='social_use_id',
            new_name='social_id',
        ),
    ]
