# Generated by Django 2.0.4 on 2018-05-15 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialtracker', '0005_auto_20180515_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=100),
        ),
    ]
